# Starship prompt config

add_newline = true

format = """
$hostname$directory$git_branch$git_status$python\
$fill\
$time\
$line_break\
$character"""

[hostname]
ssh_only = false
style = 'green'
format = '[$hostname](bold $style):'

[directory]
style = 'cyan'
truncation_length = 5
truncate_to_repo = true

[git_branch]
symbol = ''
format = ' [$branch](blue)'

[git_status]
style = '214'
format = '[$all_status$ahead_behind]($style)'
modified = '*'
staged = '+'
untracked = ''
stashed = ''
conflicted = '!'
ahead = '⇡'
behind = '⇣'
diverged = '⇕'

[python]
symbol = ''
format = '[(\($virtualenv\))](yellow)'
detect_extensions = []
detect_files = []
detect_folders = []

[fill]
symbol = ' '

[time]
disabled = false
style = '237'
format = '[$time]($style)'
time_format = '%H:%M:%S'

[character]
success_symbol = '[>>](105)'
error_symbol = '[>>](red)'

[line_break]
disabled = false

# Disable noisy modules
[package]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[cmd_duration]
disabled = true
